import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/utils/supabase/server';
import { getUserImageHistory, deleteImage } from '@/lib/storage/imageStorage';

export const dynamic = 'force-dynamic';

/**
 * GET /api/user/images
 * List all images generated by the current user
 */
export async function GET(request: NextRequest) {
  const supabase = await createClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    // Get pagination params
    const { searchParams } = new URL(request.url);
    const limit = parseInt(searchParams.get('limit') || '20', 10);
    const offset = parseInt(searchParams.get('offset') || '0', 10);
    const theme = searchParams.get('theme') || undefined;
    const status = searchParams.get('status') || undefined;

    const result = await getUserImageHistory(user.id, { limit, offset, theme, status });

    return NextResponse.json({
      success: true,
      images: result.images,
      total: result.total,
      pagination: {
        limit,
        offset,
        hasMore: result.images.length === limit,
      },
    });
  } catch (error: any) {
    console.error('[GET /api/user/images] Error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to fetch images' },
      { status: 500 }
    );
  }
}

/**
 * DELETE /api/user/images
 * Delete a specific image
 */
export async function DELETE(request: NextRequest) {
  const supabase = await createClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const { imageId } = await request.json();

    if (!imageId) {
      return NextResponse.json(
        { error: 'imageId is required' },
        { status: 400 }
      );
    }

    const result = await deleteImage(imageId, user.id);

    if (!result.success) {
      return NextResponse.json(
        { error: result.error || 'Failed to delete image' },
        { status: 404 }
      );
    }

    return NextResponse.json({
      success: true,
      message: 'Image deleted successfully',
    });
  } catch (error: any) {
    console.error('[DELETE /api/user/images] Error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to delete image' },
      { status: 500 }
    );
  }
}
